### ISSUE TITLE
Dependency management/requirments.txt

### ISSUE THREAD

**Issue by jakespracher** [khiner/notebooks#1]
Hey, was referred here from a lobste.rs comment and seems like a cool source of knowledge but I cant get some of the notebooks working. Would be great if some dependency management system/file could be used e.g. pip/requirements.txt, pipenv/pipfile, or conda/emvironment.yml.

**Comment by khiner** [comment]
In the meantime, I recommend viewing these notebooks using nbviewer.
E.g.
http://nbviewer.jupyter.org/github/khiner/notebooks/blob/master/mathematics_of_the_dft/chapter_2_complex_numbers.ipynb

**Comment by jakespracher** [comment]
Oh cool thanks! Yeah Pipenv I think would be the best option. 

https://pipenv.readthedocs.io/en/latest/basics/

Would be happy to help and make a contribution, all thats needed is the python version these notebooks use and all the packages and versions of those packages that are needed.

You can run pip freeze to see what packages you have and start from there although that will list more dependencies than you actually need (lists the dependencies of your dependences). Just look for the pacakages you remember installing from that list those should be enough.

**Comment by khiner** [comment]
Very cool, thanks for the help. I should have this done early today. I'm currently waiting for my `xcode-select` to update 😴

**Comment by khiner** [comment]
@jakespracher when you get a chance, would you please trying the install instructions I added in the root readme and let me know how it goes?

**Comment by frankk74** [comment]
Thx for sharing all of your work! 
My version of python is 3.12 and as time moves forward so do release numbers. Seems the pipenv folks don't want to support greater than version numbering*. I didn't bother submitting this as a pull request for a one line change. Although this might break things <> 3.7 so far for 3.12 things seem to be working. 

Minor proposed update to Pipfile (or left here for others to find: 

[requires]
python_version = "3"
#python_version = "3.7"

* url for reference info:

https://stackoverflow.com/questions/51492423/pipenv-how-to-specify-the-minimum-python-version-in-the-pipfile

**Comment by khiner** [comment]
@frankk74 Thanks! I switched to a simple `requirements.txt` to list (unpinned) dependencies, with Python unpinned. This is much simpler than a pyenv setup (which I tend to not use anymore), but it would be easy for folks to add the listed packages to a pyenv config if they use it.

Please lmk if you have any other suggestions!
