### ISSUE TITLE
[Coding the matrix] Solution to Problem 1.7.6

### ISSUE THREAD

**Issue by BiliBraker** [khiner/notebooks#3]
The problem description says "_Note: You are not allowed to use Python built-in procedures sum(*) and min(*)._", but in the solution, the `min()` function is used.

```
def my_min(L):
    current = None
    for x in L:
        current = x if current == None else min(current, x)
    return current

my_min([1, 2, 3])
```

**Comment by khiner** [comment]
Thanks! Please feel free to submit a pull request to improve it. Otherwise, I will add this if/when I revisit these notebooks. I don't think this is important since `min` just avoids a trivial ternary. Implementing `sum` makes more sense for absolute beginners, which I believe I do here.
